#!/bin/bash

######################################################################
# Git Prepare-commit-msg Hook Script
#
# Description:
#   This script is a Git prepare-commit-msg hook that is executed after
#   the commit message editor is opened, but before the commit message
#   is finalized. It can be used to modify or append to the commit message
#   based on certain conditions or requirements.
#
# Usage:
#   This script is automatically triggered after the commit message editor
#   is opened, allowing modifications to the commit message before finalization.
#
# Author:
#   [Your Name]
#
# Date:
#   [Date]
#
######################################################################

$(git rev-parse --show-toplevel)/.git/hooks/custom-scripts/append-changelog.sh